name = MagentaWorkDone1
type = body+head
scale = 1
filename = https://github.com/Swirla/Avatars/raw/master/MagentaWorkDone1/MagentaWorkDone1/MagentaWorkDone1.fbx
texdir = MagentaWorkDone1/textures
joint = jointEyeLeft = LeftEye
joint = jointRightHand = RightHand
joint = jointEyeRight = RightEye
joint = jointNeck = Neck
joint = jointLean = Spine
joint = jointRoot = Hips
joint = jointLeftHand = LeftHand
joint = jointHead = Head
freeJoint = LeftArm
freeJoint = LeftForeArm
freeJoint = RightArm
freeJoint = RightForeArm
jointIndex = 67 = 5
jointIndex = RightUpLeg = 28
jointIndex = LeftHandMiddle4 = 89
jointIndex = prim1.003 = 19
jointIndex = Neck = 101
jointIndex = LeftHand = 75
jointIndex = RightHandIndex2 = 63
jointIndex = RightHandRing1 = 52
jointIndex = RightHandThumb2 = 68
jointIndex = LeftLeg = 35
jointIndex = RightHandPinky1 = 47
jointIndex = RightHand = 46
jointIndex = LeftHandMiddle2 = 87
jointIndex = LeftShoulder = 72
jointIndex = LeftHandPinky4 = 79
jointIndex = prim0.004 = 4
jointIndex = prim14 = 3
jointIndex = RightHandIndex1 = 62
jointIndex = RightHandRing4 = 55
jointIndex = Head = 102
jointIndex = LeftFoot = 36
jointIndex = prim0.001 = 16
jointIndex = RightArm = 44
jointIndex = LeftArm = 73
jointIndex = RightHandRing2 = 53
jointIndex = Spine2 = 42
jointIndex = LeftHandRing2 = 82
jointIndex = prim4.002 = 21
jointIndex = LeftEye_end = 104
jointIndex = prim0.002 = 13
jointIndex = prim0.005 = 25
jointIndex = LeftHandThumb4_end = 100
jointIndex = LeftHandIndex2 = 92
jointIndex = RightHandPinky4_end = 51
jointIndex = RightHandIndex4_end = 66
jointIndex = LeftHandRing4_end = 85
jointIndex = prim0.009 = 23
jointIndex = RightHandMiddle2 = 58
jointIndex = LeftToe_End_end = 39
jointIndex = RightToe_End_end = 33
jointIndex = prim0.010 = 10
jointIndex = prim3.001 = 17
jointIndex = RightHandThumb4_end = 71
jointIndex = RightToeBase = 31
jointIndex = RightLeg = 29
jointIndex = LeftHandIndex4 = 94
jointIndex = RightHandRing4_end = 56
jointIndex = LeftHandPinky3 = 78
jointIndex = HeadTop_End = 107
jointIndex = prim0.006 = 24
jointIndex = LeftUpLeg = 34
jointIndex = RightHandPinky4 = 50
jointIndex = LeftHandMiddle3 = 88
jointIndex = LeftHandThumb1 = 96
jointIndex = RightHandMiddle3 = 59
jointIndex = prim0.011 = 12
jointIndex = prim53 = 1
jointIndex = RightHandThumb4 = 70
jointIndex = LeftToe_End = 38
jointIndex = prim0 = 6
jointIndex = Hips = 27
jointIndex = RightHandIndex3 = 64
jointIndex = LeftHandThumb2 = 97
jointIndex = HeadTop_End_end = 108
jointIndex = RightHandThumb1 = 67
jointIndex = RightShoulder = 43
jointIndex = prim1.004 = 7
jointIndex = prim0.007 = 0
jointIndex = LeftHandRing4 = 84
jointIndex = RightEye = 105
jointIndex = RightHandMiddle1 = 57
jointIndex = RightHandPinky3 = 49
jointIndex = RightHandIndex4 = 65
jointIndex = LeftHandPinky2 = 77
jointIndex = prim9 = 11
jointIndex = LeftToeBase = 37
jointIndex = RightEye_end = 106
jointIndex = LeftHandPinky1 = 76
jointIndex = LeftHandRing3 = 83
jointIndex = Spine = 40
jointIndex = LeftHandIndex3 = 93
jointIndex = RightForeArm = 45
jointIndex = RightFoot = 30
jointIndex = Spine1 = 41
jointIndex = RightHandThumb3 = 69
jointIndex = LeftHandMiddle4_end = 90
jointIndex = prim2.002 = 9
jointIndex = LeftHandIndex4_end = 95
jointIndex = LeftHandThumb3 = 98
jointIndex = LeftEye = 103
jointIndex = LeftHandThumb4 = 99
jointIndex = RightHandRing3 = 54
jointIndex = RightHandMiddle4 = 60
jointIndex = prim0.003 = 14
jointIndex = prim1 = 20
jointIndex = RightHandPinky2 = 48
jointIndex = LeftHandMiddle1 = 86
jointIndex = prim13.001 = 15
jointIndex = RightToe_End = 32
jointIndex = LeftForeArm = 74
jointIndex = LeftHandRing1 = 81
jointIndex = prim2.001 = 22
jointIndex = LeftHandPinky4_end = 80
jointIndex = prim4.003 = 18
jointIndex = RightHandMiddle4_end = 61
jointIndex = prim56 = 2
jointIndex = Armature = 26
jointIndex = prim3.002 = 8
jointIndex = LeftHandIndex1 = 91
